version: '3.2'
services:
  igma-accounts-express:
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - igma_network
    environment:
      - PORT=3000
      - DATABASE_URL="mysql://root:root@mysql:3306/igma-accounts"
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    command: sh -c "npm run generate && npm run migrate:dev && npm start "

  mysql:
    image: "mysql:5.7"
    restart: always
    container_name: mysql
    networks:
      - igma_network
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: igma-accounts
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  igma_network:
    driver: bridge

volumes:
  mysql-data: